### ISSUE TITLE
为什么 README 里面写的是 c++，但是实际是 Go

### ISSUE THREAD

**Issue by hanxuanliang** [LittleFall/tidb-hackathon-2020#4]
如题，有点疑惑

**Comment by LittleFall** [comment]
你好，我们之前聚合逻辑是用 cpp 写的，但是在意识到需要使用 ticdc 与 在 tidb后，为了与两者做兼容，把语言切换成了 golang。
因为后期时间紧急，没有来得及更新 reademe，会在之后修改。
多谢提醒
